import { Product, Category, Collection, ProductVariant } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Printed T-Shirts", slug: "Printed T-Shirts", description: "Vibrant round neck, polo and kids printed tees" },
  { id: "cat-2", name: "Caps", slug: "Caps", description: "Embroidery headwear and baseball caps" },
  { id: "cat-3", name: "Socks", slug: "Socks", description: "Crew, ankle and athletic sports socks" },
  { id: "cat-4", name: "Hand Napkins", slug: "Hand Napkins", description: "Absorbent pocket hand napkins" },
  { id: "cat-5", name: "Towels", slug: "Towels", description: "Bath, face, hand and beach towels" },
];

export const DEFAULT_COLLECTIONS: Collection[] = [
  { id: "coll-1", name: "Core Collection", slug: "core-collection" },
  { id: "coll-2", name: "Home Utilities", slug: "home-utilities" },
  { id: "coll-3", name: "Utility Gear", slug: "utility-gear" },
];

const makeVariants = (
  baseSku: string,
  sizes: string[],
  colors: string[],
  fabrics: string[],
  fits: string[],
  genders: string[],
  price: number,
  salePrice?: number
): ProductVariant[] => {
  const vars: ProductVariant[] = [];
  sizes.forEach(sz => {
    colors.forEach(col => {
      fabrics.forEach(fab => {
        fits.forEach(fit => {
          genders.forEach(gen => {
            const sku = `${baseSku}-${sz}-${col.substring(0, 3).toUpperCase()}-${fab.substring(0, 3).toUpperCase()}-${fit.substring(0, 3).toUpperCase()}`;
            vars.push({
              id: `var-${Math.random().toString(36).substr(2, 9)}`,
              sku,
              size: sz,
              color: `${col} (${fab}, ${fit} Fit)`,
              price,
              salePrice,
              stock: 50,
              reservedStock: 0,
              availableStock: 50,
              weight: 200,
              dimensions: "30x25x2 cm",
              images: [
                "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800",
                "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=800"
              ]
            });
          });
        });
      });
    });
  });
  return vars.slice(0, 18);
};

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: "round-neck-men",
    name: "Printed Round Neck T-Shirt - Men",
    slug: "printed-round-neck-tshirt-men",
    shortDescription: "Premium printed crew neck tee designed for the modern gentleman. Built with breathable fabrics.",
    description: "<p>Constructed with a double-needle stitched neckline and sleeve hems for durability. High-density graphic print on front chest.</p><h3>Care Instructions</h3><ul><li>Machine wash warm, inside out</li><li>Tumble dry medium</li><li>Do not iron print directly</li></ul>",
    category: "Printed T-Shirts",
    collection: "Core Collection",
    brand: "BLACKFAWN",
    baseSku: "RN-MEN",
    barcode: "890100000001",
    material: "100% Cotton / Cotton Blend Options",
    fabric: "Cotton Weave",
    fit: "Regular / Relaxed Options",
    gender: "men",
    gstRate: 5,
    tags: ["T-Shirts", "Men", "Printed"],
    seo: { title: "Printed Round Neck T-Shirt - Men | BLACKFAWN", description: "Premium printed crew neck tee designed for Men.", keywords: "tshirt, round neck, men, streetwear" },
    status: "active",
    isFeatured: true,
    isTrending: true,
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800"],
    rating: 4.6,
    reviewCount: 38,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 999,
    discountPrice: 799,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("RN-MEN", ["S", "M", "L", "XL", "XXL"], ["Black", "White", "Navy", "Grey"], ["100% Cotton", "Dry Fit"], ["Regular", "Relaxed"], ["Men"], 999, 799)
  },
  {
    id: "round-neck-women",
    name: "Printed Round Neck T-Shirt - Women",
    slug: "printed-round-neck-tshirt-women",
    shortDescription: "Chic and soft printed crew neck tee designed for ladies. Features a tailored comfort silhouette.",
    description: "<p>Ultra-soft cotton blend fabric designed to look good and feel breathable. Premium minimal tags.</p>",
    category: "Printed T-Shirts",
    collection: "Core Collection",
    brand: "BLACKFAWN",
    baseSku: "RN-WOMEN",
    barcode: "890100000002",
    material: "Cotton Blend",
    fabric: "Knit Cotton",
    fit: "Regular / Relaxed Options",
    gender: "women",
    gstRate: 5,
    tags: ["T-Shirts", "Women", "Printed"],
    seo: { title: "Printed Round Neck T-Shirt - Women | BLACKFAWN", description: "Soft crew neck tee for Women.", keywords: "tshirt, round neck, women" },
    status: "active",
    isFeatured: true,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800"],
    rating: 4.7,
    reviewCount: 29,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 999,
    discountPrice: 799,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("RN-WOMEN", ["S", "M", "L", "XL"], ["White", "Black", "Grey", "Red"], ["100% Cotton", "Cotton Blend"], ["Regular", "Slim Fit"], ["Women"], 999, 799)
  },
  {
    id: "round-neck-kids",
    name: "Printed Round Neck T-Shirt - Kids",
    slug: "printed-round-neck-tshirt-kids",
    shortDescription: "Comfy, vibrant, and fun printed round neck tee for children. Extremely soft on skin.",
    description: "<p>Crafted from hypoallergenic organic cotton blends to prevent skin irritation. Vibrant safe printing ink.</p>",
    category: "Printed T-Shirts",
    collection: "Kids Drop",
    brand: "BLACKFAWN",
    baseSku: "RN-KIDS",
    barcode: "890100000003",
    material: "100% Cotton",
    fabric: "Soft Jersey",
    fit: "Regular",
    gender: "unisex",
    gstRate: 5,
    tags: ["T-Shirts", "Kids", "Vibrant"],
    seo: { title: "Printed Round Neck T-Shirt - Kids | BLACKFAWN", description: "Hypoallergenic fun prints for kids.", keywords: "kids, round neck, tshirt" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&q=80&w=800"],
    rating: 4.8,
    reviewCount: 14,
    codAvailable: true,
    deliveryDaysEst: 4,
    price: 699,
    discountPrice: 499,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("RN-KIDS", ["S", "M", "L"], ["Yellow", "Red", "Blue", "Green"], ["100% Cotton"], ["Regular"], ["Kids"], 699, 499)
  },
  {
    id: "polo-men",
    name: "Printed Polo T-Shirt - Men",
    slug: "printed-polo-tshirt-men",
    shortDescription: "Classic collar printed polo shirts for semi-formal styling. Features heavy-weight knit fabric.",
    description: "<p>Ribbed collar and cuffs prevent stretching. Button-placket closure for structured neck fit.</p>",
    category: "Printed T-Shirts",
    collection: "Classics",
    brand: "BLACKFAWN",
    baseSku: "POLO-MEN",
    barcode: "890100000004",
    material: "Cotton / Dry Fit Options",
    fabric: "Pique Cotton Weave",
    fit: "Regular / Slim Options",
    gender: "men",
    gstRate: 5,
    tags: ["Polo", "Men", "Formal"],
    seo: { title: "Printed Polo T-Shirt - Men | BLACKFAWN", description: "Sophisticated pique cotton polo for Men.", keywords: "polo, collar, men" },
    status: "active",
    isTrending: true,
    images: ["https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800"],
    rating: 4.5,
    reviewCount: 42,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 1299,
    discountPrice: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("POLO-MEN", ["S", "M", "L", "XL", "XXL", "3XL"], ["Navy", "Black", "Grey", "White"], ["100% Cotton", "Dry Fit"], ["Regular", "Slim Fit"], ["Men"], 1299, 999)
  },
  {
    id: "printed-cap",
    name: "Printed Cap (Unisex)",
    slug: "printed-cap-unisex",
    shortDescription: "Signature structure baseball cap featuring flat embroidery tag. One size fits all adjustment.",
    description: "<p>Unstructured 6-panel design with brass buckle rear slide adjustment lock. Sweatband built inside.</p>",
    category: "Caps",
    collection: "Utility Gear",
    brand: "BLACKFAWN",
    baseSku: "CAP-UNISEX",
    barcode: "890100000005",
    material: "150g Heavy Canvas Cotton",
    fabric: "Canvas",
    fit: "Regular Adjustment",
    gender: "unisex",
    gstRate: 18,
    tags: ["Cap", "Unisex", "Headwear"],
    seo: { title: "Printed Cap (Unisex) | BLACKFAWN", description: "Heavy embroidery custom adjust caps.", keywords: "cap, hat, gear" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"],
    rating: 4.4,
    reviewCount: 22,
    codAvailable: true,
    deliveryDaysEst: 4,
    price: 599,
    discountPrice: 449,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-cap-1", sku: "CAP-UNI-OS-BLK", size: "Free Size", color: "Black", price: 599, salePrice: 449, stock: 100, reservedStock: 0, availableStock: 100, images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-cap-2", sku: "CAP-UNI-OS-WHT", size: "Free Size", color: "White", price: 599, salePrice: 449, stock: 80, reservedStock: 0, availableStock: 80, images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-cap-3", sku: "CAP-UNI-OS-NVY", size: "Free Size", color: "Navy", price: 599, salePrice: 449, stock: 50, reservedStock: 0, availableStock: 50, images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"] }
    ]
  },
  {
    id: "printed-socks",
    name: "Printed Socks (Unisex)",
    slug: "printed-socks-unisex",
    shortDescription: "Ultra-comfy socks designed with reinforced heels and custom length options.",
    description: "<p>Padded cushion footbed layout keeps feet sweat-free and absorbs active impact during workouts.</p>",
    category: "Socks",
    collection: "Utility Gear",
    brand: "BLACKFAWN",
    baseSku: "SOCK-UNISEX",
    barcode: "890100000006",
    material: "Cotton Lycra Blend",
    fabric: "Elastane Weave",
    fit: "Snug fit",
    gender: "unisex",
    gstRate: 12,
    tags: ["Socks", "Unisex", "Athletic"],
    seo: { title: "Printed Socks (Unisex) | BLACKFAWN", description: "Padded active athletic socks for Unisex.", keywords: "socks, activewear" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"],
    rating: 4.6,
    reviewCount: 56,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 399,
    discountPrice: 249,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-sock-1", sku: "SOCK-UNI-ANK-MEN", size: "Men", color: "Ankle Length", price: 399, salePrice: 249, stock: 120, reservedStock: 0, availableStock: 120, images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-sock-2", sku: "SOCK-UNI-CRE-WOM", size: "Women", color: "Crew Length", price: 399, salePrice: 249, stock: 100, reservedStock: 0, availableStock: 100, images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-sock-3", sku: "SOCK-UNI-SPO-KID", size: "Kids", color: "Sports Socks", price: 399, salePrice: 249, stock: 50, reservedStock: 0, availableStock: 50, images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"] }
    ]
  },
  {
    id: "hand-napkin",
    name: "Printed Hand Napkin",
    slug: "printed-hand-napkin",
    shortDescription: "Pocket hand napkins made of heavy loop premium absorbent Terry cotton weave.",
    description: "<p>Fast drying loop structures ensure rapid moisture absorption. Easy carry styling.</p>",
    category: "Hand Napkins",
    collection: "Home Utilities",
    brand: "BLACKFAWN",
    baseSku: "NAPKIN",
    barcode: "890100000007",
    material: "Terry Cotton Weave",
    fabric: "Terry loops",
    fit: "Square",
    gender: "unisex",
    gstRate: 12,
    tags: ["Napkin", "Home", "Absorbent"],
    seo: { title: "Printed Hand Napkins | BLACKFAWN", description: "100% Terry cotton absorbent napkins.", keywords: "napkin, towels" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&q=80&w=800"],
    rating: 4.3,
    reviewCount: 18,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 249,
    discountPrice: 149,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-nap-1", sku: "NAP-COT-SML", size: "Small", color: "Cotton Weave", price: 249, salePrice: 149, stock: 200, reservedStock: 0, availableStock: 200, images: ["https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-nap-2", sku: "NAP-TER-MED", size: "Medium", color: "Terry Cotton Weave", price: 299, salePrice: 199, stock: 150, reservedStock: 0, availableStock: 150, images: ["https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&q=80&w=800"] }
    ]
  },
  {
    id: "printed-towels",
    name: "Printed Towels",
    slug: "printed-towels",
    shortDescription: "Vibrant high GSM printed towels in multiple variants for bath, beach and hands.",
    description: "<p>Luxurious 500 GSM loop cotton construction. Quick drying, odor-repelling fabric layer.</p>",
    category: "Towels",
    collection: "Home Utilities",
    brand: "BLACKFAWN",
    baseSku: "TOWEL",
    barcode: "890100000008",
    material: "100% Organic Cotton",
    fabric: "High GSM loops",
    fit: "Rectangular",
    gender: "unisex",
    gstRate: 12,
    tags: ["Towels", "Bath", "Beach"],
    seo: { title: "Printed Bath & Beach Towels | BLACKFAWN", description: "Organic high-absorbing custom print towels.", keywords: "towel, bath, beach" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"],
    rating: 4.6,
    reviewCount: 45,
    codAvailable: true,
    deliveryDaysEst: 4,
    price: 1199,
    discountPrice: 899,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-towl-1", sku: "TOWL-FAC-OS", size: "30x30 cm", color: "Face Towel", price: 399, salePrice: 299, stock: 300, reservedStock: 0, availableStock: 300, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-towl-2", sku: "TOWL-HND-OS", size: "40x60 cm", color: "Hand Towel", price: 599, salePrice: 449, stock: 250, reservedStock: 0, availableStock: 250, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-towl-3", sku: "TOWL-BTH-OS", size: "70x140 cm", color: "Bath Towel", price: 1199, salePrice: 899, stock: 180, reservedStock: 0, availableStock: 180, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-towl-4", sku: "TOWL-BCH-OS", size: "100x180 cm", color: "Beach Towel", price: 1599, salePrice: 1299, stock: 100, reservedStock: 0, availableStock: 100, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] }
    ]
  }
];
