import { Product, Category, Collection, ProductVariant } from './types';

export const DEFAULT_CATEGORIES: Category[] = [
  { id: "cat-1", name: "Printed T-Shirts", slug: "Printed T-Shirts", description: "Vibrant round neck, polo and kids printed tees" },
  { id: "cat-2", name: "Caps", slug: "Caps", description: "Embroidery headwear and baseball caps" },
  { id: "cat-3", name: "Socks", slug: "Socks", description: "Crew, ankle and athletic sports socks" },
  { id: "cat-4", name: "Hand Napkins", slug: "Hand Napkins", description: "Absorbent pocket hand napkins" },
  { id: "cat-5", name: "Towels", slug: "Towels", description: "Bath, face, hand and beach towels" },
  { id: "cat-6", name: "Hampers & Gifting", slug: "Hampers & Gifting", description: "Curated luxury gift hampers and artisanal boxes" },
];

export const DEFAULT_COLLECTIONS: Collection[] = [
  { id: "coll-1", name: "Core Collection", slug: "core-collection" },
  { id: "coll-2", name: "Home Utilities", slug: "home-utilities" },
  { id: "coll-3", name: "Utility Gear", slug: "utility-gear" },
  { id: "coll-4", name: "Premium Gift Hampers", slug: "Premium Gift Hampers" },
  { id: "coll-5", name: "Personalized Hampers", slug: "Personalized Hampers" },
  { id: "coll-6", name: "Corporate Hampers", slug: "Corporate Hampers" },
  { id: "coll-7", name: "Festival Hampers", slug: "Festival Hampers" },
  { id: "coll-8", name: "Couple Hampers", slug: "Couple Hampers" },
  { id: "coll-9", name: "Kids Hampers", slug: "Kids Hampers" },
];

const makeVariants = (
  baseSku: string,
  sizes: string[],
  colors: string[],
  fabrics: string[],
  fits: string[],
  genders: string[],
  price: number,
  salePrice?: number
): ProductVariant[] => {
  const vars: ProductVariant[] = [];
  sizes.forEach(sz => {
    colors.forEach(col => {
      fabrics.forEach(fab => {
        fits.forEach(fit => {
          genders.forEach(gen => {
            const sku = `${baseSku}-${sz}-${col.substring(0, 3).toUpperCase()}-${fab.substring(0, 3).toUpperCase()}-${fit.substring(0, 3).toUpperCase()}`;
            vars.push({
              id: `var-${Math.random().toString(36).substr(2, 9)}`,
              sku,
              size: sz,
              color: `${col} (${fab}, ${fit} Fit)`,
              price,
              salePrice,
              stock: 50,
              reservedStock: 0,
              availableStock: 50,
              weight: 200,
              dimensions: "30x25x2 cm",
              images: [
                "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800",
                "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&q=80&w=800"
              ]
            });
          });
        });
      });
    });
  });
  return vars.slice(0, 18);
};

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: "round-neck-men",
    name: "Printed Round Neck T-Shirt - Men",
    slug: "printed-round-neck-tshirt-men",
    shortDescription: "Premium printed crew neck tee designed for the modern gentleman. Built with breathable fabrics.",
    description: "<p>Constructed with a double-needle stitched neckline and sleeve hems for durability. High-density graphic print on front chest.</p><h3>Care Instructions</h3><ul><li>Machine wash warm, inside out</li><li>Tumble dry medium</li><li>Do not iron print directly</li></ul>",
    category: "Printed T-Shirts",
    collection: "Core Collection",
    brand: "BLACKFAWN",
    baseSku: "RN-MEN",
    barcode: "890100000001",
    material: "100% Cotton / Cotton Blend Options",
    fabric: "Cotton Weave",
    fit: "Regular / Relaxed Options",
    gender: "men",
    gstRate: 5,
    tags: ["T-Shirts", "Men", "Printed"],
    seo: { title: "Printed Round Neck T-Shirt - Men | BLACKFAWN", description: "Premium printed crew neck tee designed for Men.", keywords: "tshirt, round neck, men, streetwear" },
    status: "active",
    isFeatured: true,
    isTrending: true,
    images: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=800"],
    rating: 4.6,
    reviewCount: 38,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 999,
    discountPrice: 799,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("RN-MEN", ["S", "M", "L", "XL", "XXL"], ["Black", "White", "Navy", "Grey"], ["100% Cotton", "Dry Fit"], ["Regular", "Relaxed"], ["Men"], 999, 799)
  },
  {
    id: "round-neck-women",
    name: "Printed Round Neck T-Shirt - Women",
    slug: "printed-round-neck-tshirt-women",
    shortDescription: "Chic and soft printed crew neck tee designed for ladies. Features a tailored comfort silhouette.",
    description: "<p>Ultra-soft cotton blend fabric designed to look good and feel breathable. Premium minimal tags.</p>",
    category: "Printed T-Shirts",
    collection: "Core Collection",
    brand: "BLACKFAWN",
    baseSku: "RN-WOMEN",
    barcode: "890100000002",
    material: "Cotton Blend",
    fabric: "Knit Cotton",
    fit: "Regular / Relaxed Options",
    gender: "women",
    gstRate: 5,
    tags: ["T-Shirts", "Women", "Printed"],
    seo: { title: "Printed Round Neck T-Shirt - Women | BLACKFAWN", description: "Soft crew neck tee for Women.", keywords: "tshirt, round neck, women" },
    status: "active",
    isFeatured: true,
    images: ["https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=800"],
    rating: 4.7,
    reviewCount: 29,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 999,
    discountPrice: 799,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("RN-WOMEN", ["S", "M", "L", "XL"], ["White", "Black", "Grey", "Red"], ["100% Cotton", "Cotton Blend"], ["Regular", "Slim Fit"], ["Women"], 999, 799)
  },
  {
    id: "round-neck-kids",
    name: "Printed Round Neck T-Shirt - Kids",
    slug: "printed-round-neck-tshirt-kids",
    shortDescription: "Comfy, vibrant, and fun printed round neck tee for children. Extremely soft on skin.",
    description: "<p>Crafted from hypoallergenic organic cotton blends to prevent skin irritation. Vibrant safe printing ink.</p>",
    category: "Printed T-Shirts",
    collection: "Kids Drop",
    brand: "BLACKFAWN",
    baseSku: "RN-KIDS",
    barcode: "890100000003",
    material: "100% Cotton",
    fabric: "Soft Jersey",
    fit: "Regular",
    gender: "unisex",
    gstRate: 5,
    tags: ["T-Shirts", "Kids", "Vibrant"],
    seo: { title: "Printed Round Neck T-Shirt - Kids | BLACKFAWN", description: "Hypoallergenic fun prints for kids.", keywords: "kids, round neck, tshirt" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&q=80&w=800"],
    rating: 4.8,
    reviewCount: 14,
    codAvailable: true,
    deliveryDaysEst: 4,
    price: 699,
    discountPrice: 499,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("RN-KIDS", ["S", "M", "L"], ["Yellow", "Red", "Blue", "Green"], ["100% Cotton"], ["Regular"], ["Kids"], 699, 499)
  },
  {
    id: "polo-men",
    name: "Printed Polo T-Shirt - Men",
    slug: "printed-polo-tshirt-men",
    shortDescription: "Classic collar printed polo shirts for semi-formal styling. Features heavy-weight knit fabric.",
    description: "<p>Ribbed collar and cuffs prevent stretching. Button-placket closure for structured neck fit.</p>",
    category: "Printed T-Shirts",
    collection: "Classics",
    brand: "BLACKFAWN",
    baseSku: "POLO-MEN",
    barcode: "890100000004",
    material: "Cotton / Dry Fit Options",
    fabric: "Pique Cotton Weave",
    fit: "Regular / Slim Options",
    gender: "men",
    gstRate: 5,
    tags: ["Polo", "Men", "Formal"],
    seo: { title: "Printed Polo T-Shirt - Men | BLACKFAWN", description: "Sophisticated pique cotton polo for Men.", keywords: "polo, collar, men" },
    status: "active",
    isTrending: true,
    images: ["https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&q=80&w=800"],
    rating: 4.5,
    reviewCount: 42,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 1299,
    discountPrice: 999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: makeVariants("POLO-MEN", ["S", "M", "L", "XL", "XXL", "3XL"], ["Navy", "Black", "Grey", "White"], ["100% Cotton", "Dry Fit"], ["Regular", "Slim Fit"], ["Men"], 1299, 999)
  },
  {
    id: "printed-cap",
    name: "Printed Cap (Unisex)",
    slug: "printed-cap-unisex",
    shortDescription: "Signature structure baseball cap featuring flat embroidery tag. One size fits all adjustment.",
    description: "<p>Unstructured 6-panel design with brass buckle rear slide adjustment lock. Sweatband built inside.</p>",
    category: "Caps",
    collection: "Utility Gear",
    brand: "BLACKFAWN",
    baseSku: "CAP-UNISEX",
    barcode: "890100000005",
    material: "150g Heavy Canvas Cotton",
    fabric: "Canvas",
    fit: "Regular Adjustment",
    gender: "unisex",
    gstRate: 18,
    tags: ["Cap", "Unisex", "Headwear"],
    seo: { title: "Printed Cap (Unisex) | BLACKFAWN", description: "Heavy embroidery custom adjust caps.", keywords: "cap, hat, gear" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"],
    rating: 4.4,
    reviewCount: 22,
    codAvailable: true,
    deliveryDaysEst: 4,
    price: 599,
    discountPrice: 449,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-cap-1", sku: "CAP-UNI-OS-BLK", size: "Free Size", color: "Black", price: 599, salePrice: 449, stock: 100, reservedStock: 0, availableStock: 100, images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-cap-2", sku: "CAP-UNI-OS-WHT", size: "Free Size", color: "White", price: 599, salePrice: 449, stock: 80, reservedStock: 0, availableStock: 80, images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-cap-3", sku: "CAP-UNI-OS-NVY", size: "Free Size", color: "Navy", price: 599, salePrice: 449, stock: 50, reservedStock: 0, availableStock: 50, images: ["https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=800"] }
    ]
  },
  {
    id: "printed-socks",
    name: "Printed Socks (Unisex)",
    slug: "printed-socks-unisex",
    shortDescription: "Ultra-comfy socks designed with reinforced heels and custom length options.",
    description: "<p>Padded cushion footbed layout keeps feet sweat-free and absorbs active impact during workouts.</p>",
    category: "Socks",
    collection: "Utility Gear",
    brand: "BLACKFAWN",
    baseSku: "SOCK-UNISEX",
    barcode: "890100000006",
    material: "Cotton Lycra Blend",
    fabric: "Elastane Weave",
    fit: "Snug fit",
    gender: "unisex",
    gstRate: 12,
    tags: ["Socks", "Unisex", "Athletic"],
    seo: { title: "Printed Socks (Unisex) | BLACKFAWN", description: "Padded active athletic socks for Unisex.", keywords: "socks, activewear" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"],
    rating: 4.6,
    reviewCount: 56,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 399,
    discountPrice: 249,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-sock-1", sku: "SOCK-UNI-ANK-MEN", size: "Men", color: "Ankle Length", price: 399, salePrice: 249, stock: 120, reservedStock: 0, availableStock: 120, images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-sock-2", sku: "SOCK-UNI-CRE-WOM", size: "Women", color: "Crew Length", price: 399, salePrice: 249, stock: 100, reservedStock: 0, availableStock: 100, images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-sock-3", sku: "SOCK-UNI-SPO-KID", size: "Kids", color: "Sports Socks", price: 399, salePrice: 249, stock: 50, reservedStock: 0, availableStock: 50, images: ["https://images.unsplash.com/photo-1582966772680-860e372bb558?auto=format&fit=crop&q=80&w=800"] }
    ]
  },
  {
    id: "hand-napkin",
    name: "Printed Hand Napkin",
    slug: "printed-hand-napkin",
    shortDescription: "Pocket hand napkins made of heavy loop premium absorbent Terry cotton weave.",
    description: "<p>Fast drying loop structures ensure rapid moisture absorption. Easy carry styling.</p>",
    category: "Hand Napkins",
    collection: "Home Utilities",
    brand: "BLACKFAWN",
    baseSku: "NAPKIN",
    barcode: "890100000007",
    material: "Terry Cotton Weave",
    fabric: "Terry loops",
    fit: "Square",
    gender: "unisex",
    gstRate: 12,
    tags: ["Napkin", "Home", "Absorbent"],
    seo: { title: "Printed Hand Napkins | BLACKFAWN", description: "100% Terry cotton absorbent napkins.", keywords: "napkin, towels" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&q=80&w=800"],
    rating: 4.3,
    reviewCount: 18,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 249,
    discountPrice: 149,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-nap-1", sku: "NAP-COT-SML", size: "Small", color: "Cotton Weave", price: 249, salePrice: 149, stock: 200, reservedStock: 0, availableStock: 200, images: ["https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-nap-2", sku: "NAP-TER-MED", size: "Medium", color: "Terry Cotton Weave", price: 299, salePrice: 199, stock: 150, reservedStock: 0, availableStock: 150, images: ["https://images.unsplash.com/photo-1616627561950-9f746e330187?auto=format&fit=crop&q=80&w=800"] }
    ]
  },
  {
    id: "printed-towels",
    name: "Printed Towels",
    slug: "printed-towels",
    shortDescription: "Vibrant high GSM printed towels in multiple variants for bath, beach and hands.",
    description: "<p>Luxurious 500 GSM loop cotton construction. Quick drying, odor-repelling fabric layer.</p>",
    category: "Towels",
    collection: "Home Utilities",
    brand: "BLACKFAWN",
    baseSku: "TOWEL",
    barcode: "890100000008",
    material: "100% Organic Cotton",
    fabric: "High GSM loops",
    fit: "Rectangular",
    gender: "unisex",
    gstRate: 12,
    tags: ["Towels", "Bath", "Beach"],
    seo: { title: "Printed Bath & Beach Towels | BLACKFAWN", description: "Organic high-absorbing custom print towels.", keywords: "towel, bath, beach" },
    status: "active",
    images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"],
    rating: 4.6,
    reviewCount: 45,
    codAvailable: true,
    deliveryDaysEst: 4,
    price: 1199,
    discountPrice: 899,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      { id: "var-towl-1", sku: "TOWL-FAC-OS", size: "30x30 cm", color: "Face Towel", price: 399, salePrice: 299, stock: 300, reservedStock: 0, availableStock: 300, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-towl-2", sku: "TOWL-HND-OS", size: "40x60 cm", color: "Hand Towel", price: 599, salePrice: 449, stock: 250, reservedStock: 0, availableStock: 250, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-towl-3", sku: "TOWL-BTH-OS", size: "70x140 cm", color: "Bath Towel", price: 1199, salePrice: 899, stock: 180, reservedStock: 0, availableStock: 180, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] },
      { id: "var-towl-4", sku: "TOWL-BCH-OS", size: "100x180 cm", color: "Beach Towel", price: 1599, salePrice: 1299, stock: 100, reservedStock: 0, availableStock: 100, images: ["https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&q=80&w=800"] }
    ]
  },
  {
    id: "hamp-royal-gold",
    name: "The Royal Black & Gold Luxury Box",
    slug: "royal-black-gold-luxury-box",
    shortDescription: "Ultra-exclusive gift hamper containing premium silk accessories, gold foil embossed journals, and artisanal brass keepsakes.",
    description: "<p>Elevate corporate and personal celebrations with the signature BLACKFAWN Royal Box. Encased in a textured matte black velvet box lined with champagne gold satin.</p><h3>Included In This Box</h3><ul><li>Handcrafted Leatherette Journal with Gold Edging</li><li>Signature BLACKFAWN Brushed Brass Pen</li><li>Aromatic Vanilla & Cedarwood Soy Candle (200g)</li><li>Gourmet Dark Chocolate Truffles Box</li></ul>",
    category: "Hampers & Gifting",
    collection: "Premium Gift Hampers",
    brand: "BLACKFAWN",
    baseSku: "HAMP-ROYAL-01",
    barcode: "890100000010",
    material: "Velvet Box & Brass Hardware",
    fabric: "Satin Lining",
    fit: "Standard Hamper Box",
    gender: "unisex",
    gstRate: 18,
    tags: ["Hamper", "Luxury", "Gift Box", "Gold"],
    seo: { title: "The Royal Black & Gold Luxury Box | BLACKFAWN Gifting", description: "Ultra-exclusive luxury gift hamper in matte black velvet.", keywords: "gift hamper, corporate hamper, luxury gift" },
    status: "active",
    isFeatured: true,
    isBestSeller: true,
    isNewArrival: true,
    images: ["/1.jpeg", "/2.jpeg", "/3.jpeg"],
    rating: 5.0,
    reviewCount: 19,
    codAvailable: true,
    deliveryDaysEst: 2,
    price: 4999,
    discountPrice: 3999,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: "var-hamp-1-std",
        sku: "HAMP-ROYAL-STD",
        size: "Standard Gift Box",
        color: "Black & Gold",
        price: 4999,
        salePrice: 3999,
        stock: 35,
        reservedStock: 0,
        availableStock: 35,
        images: ["/1.jpeg", "/2.jpeg", "/3.jpeg"]
      }
    ]
  },
  {
    id: "hamp-monogram-deluxe",
    name: "Personalized Atelier Keepsake Hamper",
    slug: "personalized-atelier-keepsake-hamper",
    shortDescription: "Bespoke gift box with laser-engraved monogram options, custom greeting cards, and luxury accessories.",
    description: "<p>Add a personal touch to your gifting experience with custom name engraving on velvet brass tags and bespoke stationery sets.</p>",
    category: "Hampers & Gifting",
    collection: "Personalized Hampers",
    brand: "BLACKFAWN",
    baseSku: "HAMP-PERS-02",
    barcode: "890100000011",
    material: "Hardboard & Gold Foil",
    fabric: "Linen Lining",
    fit: "Custom Box",
    gender: "unisex",
    gstRate: 18,
    tags: ["Personalized", "Hamper", "Monogram"],
    seo: { title: "Personalized Atelier Keepsake Hamper | BLACKFAWN", description: "Custom monogram laser engraved luxury hampers.", keywords: "personalized hamper, custom gifting" },
    status: "active",
    isFeatured: true,
    images: ["/4.jpeg", "/5.jpeg", "/6.jpeg"],
    rating: 4.9,
    reviewCount: 14,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 3499,
    discountPrice: 2899,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: "var-hamp-2-std",
        sku: "HAMP-PERS-STD",
        size: "Bespoke Set",
        color: "Ivory & Champagne",
        price: 3499,
        salePrice: 2899,
        stock: 25,
        reservedStock: 0,
        availableStock: 25,
        images: ["/4.jpeg", "/5.jpeg", "/6.jpeg"]
      }
    ]
  },
  {
    id: "hamp-executive-corporate",
    name: "The Executive Leadership Corporate Suite",
    slug: "executive-leadership-corporate-suite",
    shortDescription: "Refined corporate gifting collection designed for C-suite clients and valued enterprise partners.",
    description: "<p>Impress VIP clients with our executive suite featuring stainless steel thermal tumblers, leather tech organizers, and signature espresso beans.</p>",
    category: "Hampers & Gifting",
    collection: "Corporate Hampers",
    brand: "BLACKFAWN",
    baseSku: "HAMP-CORP-03",
    barcode: "890100000012",
    material: "Matte Black Hard Box",
    fabric: "High-density Foam insert",
    fit: "Executive Suite",
    gender: "unisex",
    gstRate: 18,
    tags: ["Corporate", "Executive", "B2B", "Hamper"],
    seo: { title: "The Executive Leadership Corporate Suite | BLACKFAWN", description: "High-end corporate gift hampers for executives.", keywords: "corporate gifting, executive hamper" },
    status: "active",
    isBestSeller: true,
    images: ["/7.jpeg", "/8.jpeg", "/9.jpeg"],
    rating: 4.8,
    reviewCount: 31,
    codAvailable: true,
    deliveryDaysEst: 2,
    price: 5999,
    discountPrice: 4799,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: "var-hamp-3-std",
        sku: "HAMP-CORP-STD",
        size: "Corporate Pack",
        color: "Stealth Black",
        price: 5999,
        salePrice: 4799,
        stock: 50,
        reservedStock: 0,
        availableStock: 50,
        images: ["/7.jpeg", "/8.jpeg", "/9.jpeg"]
      }
    ]
  },
  {
    id: "hamp-festive-celebration",
    name: "Golden Festive Celebration Hamper",
    slug: "golden-festive-celebration-hamper",
    shortDescription: "A grand festive box curated with brass diyas, dry fruit assortments, and luxury home fragrances.",
    description: "<p>Celebrate auspicious occasions with timeless elegance. Contains hand-hammered brass artifacts and organic treats.</p>",
    category: "Hampers & Gifting",
    collection: "Festival Hampers",
    brand: "BLACKFAWN",
    baseSku: "HAMP-FEST-04",
    barcode: "890100000013",
    material: "Gold Embossed Wood Box",
    fabric: "Silk Brocade",
    fit: "Festival Edition",
    gender: "unisex",
    gstRate: 18,
    tags: ["Festive", "Diwali", "Celebration", "Gold"],
    seo: { title: "Golden Festive Celebration Hamper | BLACKFAWN", description: "Festive hampers with brass diyas and gourmet sweets.", keywords: "festive hamper, diwali gift box" },
    status: "active",
    isNewArrival: true,
    images: ["/10.jpeg", "/11.jpeg"],
    rating: 4.9,
    reviewCount: 22,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 4299,
    discountPrice: 3499,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: "var-hamp-4-std",
        sku: "HAMP-FEST-STD",
        size: "Grand Box",
        color: "Gold & Crimson",
        price: 4299,
        salePrice: 3499,
        stock: 40,
        reservedStock: 0,
        availableStock: 40,
        images: ["/10.jpeg", "/11.jpeg"]
      }
    ]
  },
  {
    id: "hamp-couple-eternity",
    name: "His & Hers Eternity Celebration Hamper",
    slug: "his-hers-eternity-celebration-hamper",
    shortDescription: "Romantic dual luxury box containing paired crystal goblets, scented massage candles, and matching keepsakes.",
    description: "<p>The ultimate anniversary or wedding gift set for couples. Elegantly paired items designed for shared luxury moments.</p>",
    category: "Hampers & Gifting",
    collection: "Couple Hampers",
    brand: "BLACKFAWN",
    baseSku: "HAMP-COUPLE-05",
    barcode: "890100000014",
    material: "Dual Drawer Gift Chest",
    fabric: "Velvet Pad",
    fit: "Twin Set",
    gender: "unisex",
    gstRate: 18,
    tags: ["Couple", "Anniversary", "His and Hers", "Wedding"],
    seo: { title: "His & Hers Eternity Celebration Hamper | BLACKFAWN", description: "Luxury anniversary gift hamper for couples.", keywords: "couple hamper, wedding gift box" },
    status: "active",
    isFeatured: true,
    images: ["/12.jpeg", "/13.jpeg"],
    rating: 5.0,
    reviewCount: 16,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 5499,
    discountPrice: 4299,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: "var-hamp-5-std",
        sku: "HAMP-COUPLE-STD",
        size: "Dual Box Set",
        color: "Black & Rose Gold",
        price: 5499,
        salePrice: 4299,
        stock: 20,
        reservedStock: 0,
        availableStock: 20,
        images: ["/12.jpeg", "/13.jpeg"]
      }
    ]
  },
  {
    id: "hamp-junior-wonder",
    name: "Little Prince & Princess Joy Gift Box",
    slug: "little-prince-princess-joy-gift-box",
    shortDescription: "Delightful kids hamper with organic plush toys, customized storybooks, and premium treats.",
    description: "<p>Specially curated for young ones using child-safe organic materials, fun games, and sweet surprises.</p>",
    category: "Hampers & Gifting",
    collection: "Kids Hampers",
    brand: "BLACKFAWN",
    baseSku: "HAMP-KIDS-06",
    barcode: "890100000015",
    material: "Pastel Hardboard Box",
    fabric: "Soft Cotton Pouch",
    fit: "Kids Box",
    gender: "unisex",
    gstRate: 12,
    tags: ["Kids", "Birthday", "Child Gift", "Joy"],
    seo: { title: "Little Prince & Princess Joy Gift Box | BLACKFAWN", description: "Vibrant and safe luxury gift boxes for children.", keywords: "kids hamper, child gift box" },
    status: "active",
    images: ["/14.jpeg", "/1.jpeg"],
    rating: 4.7,
    reviewCount: 9,
    codAvailable: true,
    deliveryDaysEst: 3,
    price: 2799,
    discountPrice: 2199,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    variants: [
      {
        id: "var-hamp-6-std",
        sku: "HAMP-KIDS-STD",
        size: "Joy Edition",
        color: "Pastel Gold",
        price: 2799,
        salePrice: 2199,
        stock: 30,
        reservedStock: 0,
        availableStock: 30,
        images: ["/14.jpeg", "/1.jpeg"]
      }
    ]
  }
];
